FROM alpine:3.21 AS base

ENV TSHOCKURL="https://github.com/Pryaxis/TShock/releases/download/v6.1.0/TShock-6.1.0-for-Terraria-1.4.5.6-linux-arm64-Release.zip"

RUN apk add --no-cache wget unzip
RUN wget $TSHOCKURL -O /tshock.zip && \
    mkdir /tshock && \
    unzip /tshock.zip -d /tshock && \
    rm /tshock.zip

RUN tar -xf /tshock/TShock-Beta-linux-arm64-Release.tar -C /tshock && \
    rm /tshock/TShock-Beta-linux-arm64-Release.tar

FROM mcr.microsoft.com/dotnet/runtime:9.0-noble-arm64v8

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends libicu-dev && \
    rm -rf /var/lib/apt/lists/*

COPY --from=base /tshock/ /tshock/

RUN chmod +x /tshock/TShock.Server

RUN echo '#!/bin/bash\n/tshock/TShock.Server -configpath /data -worldselectpath /data/worlds -logpath /data/logs "$@"' > /tshock/start.sh && \
    chmod +x /tshock/start.sh

VOLUME ["/data"]
EXPOSE 7777
WORKDIR /tshock
ENTRYPOINT ["/bin/bash", "/tshock/start.sh"]

# docker build --platform linux/arm64 -t terraria-docker:latest -f arm64/dockerfile .
# docker run -it -p 7777:7777 -v /home/$USER/terraria:/data --name terraria-docker terraria-docker:latest
